Practicing what was learnt on day 1

In [1]:

import numpy as np

def neural_network(inputs):
    weights=np.array([.7,.9,.16])
    output=inputs.dot(weights)
    return output
input1= np.array([4,5,7])
print(neural_network(input1))

8.42


# Day 2 Begins here

## Neural network with multple input and multiple output
We have a vector of inputs and one single wegiht vector which we use to predict multiple outputs using single weight vector

In [8]:
def neural_networkSWMOSW(inputs):
    weights=np.array([.7,.9,.16])
    output=element_multiplication(inputs,weights)
    return output
def element_multiplication(vec_a,vec_b):
    assert len(vec_a)==len(vec_b)
    newlst=np.zeros(len(vec_a))
    for i in range(len(vec_b)):
        newlst[i]=vec_a[i]*vec_b[i]
    return newlst

Next we call the above neural network by passing an input array

In [9]:
in1=np.array([50,70,90])
print(neural_networkSWMOSW(in1))

[35.  63.  14.4]


## Neural Network with mutiple input and multiple outputs using multiple weights for each output
Input here will be a vector defining different input features and the output will be a a vector defining multiple outputs.
We need to have a matrix of weights for each output

In [72]:
def neural_networkSIMOMW(inputs):
    weights=np.array([[.1,.2,.3],[.4,.5,.6],[.7,.8,.9]])
    outputlst=inputs.dot(weights)
    return outputlst
def weighted_sum(inputs,weights):
    return inputs.dot(weights)

In [73]:
in1=np.array([50,70,90])
print(neural_networkSIMOMW(in1))

[ 96. 117. 138.]


## Neural network which works at multiple layers

I will here define an array for input value and then create multiple layers for network using different array of weights

In [64]:
# code begins

In [69]:
def neural_networkMIMWMLMO(vec):
    layer_1=np.array([[.1,.2,.3],[.4,.5,.6],[.7,.8,.9]])
    layer_2=np.array([[.11,.12,.13],[.14,.15,.16],[.17,.18,.19]])
    layer1=vec.dot(layer_1)
    layerfnn=layer1.dot(layer_2)
    return layerfnn

In [68]:
neural_networkMIMWMLMO(in1)

array([50.4 , 53.91, 57.42])